import '@/styles/main.scss'

import Footer from '@/components/layout/footer/footer'
import Header from '@/components/layout/header/header'
import { Inter } from 'next/font/google'
import Main from '@/components/layout/main/main'
import type { Metadata } from 'next'
import { SortOptionProvider } from '@/context/sort-option.context'
import Toast from '@/components/general/toast/toast'
import { ToastProvider } from '@/context/toast.context'

const inter = Inter({ subsets: ['latin'] })

// TODO: add site config
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const dynamic = 'force-dynamic'

interface Props {
  children: React.ReactNode
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToastProvider>
          <Toast />
          <Header />
          <SortOptionProvider>
            <Main>{children}</Main>
            <Footer />
          </SortOptionProvider>
        </ToastProvider>
      </body>
    </html>
  )
}

export default RootLayout
